version: 0.0
os: linux
files:
  - source: /
    destination: /svc/web/api-laravel # 배포 위치 지정 
    overwrite: true # 덮어쓰기 
file_exists_behavior: OVERWRITE
permissions:  # CodeDeploy에서 EC2로 배포한 파일 및 폴더 권한 처리
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user