version: 0.0
os: linux
files:
  - source: /
    destination: /svc/web/api-laravel # 배포 위치 지정 
file_exists_behavior: OVERWRITE # 덮어쓰기  
permissions:  # CodeDeploy에서 EC2로 배포한 파일 및 폴더 권한 처리
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    # EC2경로가 아니라 배포할 소스 코드에 shell script있어야 함
    - location: scripts/post-processing.sh
      runas: root